version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ilias-app-api:0.1
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file: .env